spring:
  application:
    name: EUREKA-HA
---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: 172.28.186.75
  client:
    serviceUrl:
      defaultZone: http://172.28.186.75:8762/eureka/,http://peer3:8763/eureka/
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: 172.28.186.75
  client:
    serviceUrl:
      defaultZone: http://172.28.186.75:8761/eureka/,http://172.28.186.75:8763/eureka/
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: 172.28.186.75
  client:
    serviceUrl:
      defaultZone: http://172.28.186.75:8761/eureka/,http://172.28.186.75:8762/eureka/